- name: Install TightVNC server
  ansible.builtin.package:
    name:
      - tightvncserver
    state: present

- name: Check if vnc_user is defined
  ansible.builtin.debug:
    msg: "vnc_user is set to {{ vnc_user }}"

- name: Create .vnc directory
  ansible.builtin.file:
    path: "/home/{{ vnc_user }}/.vnc"
    state: directory
    mode: '0700'  # Set permissions so only the user can access
    owner: "{{ vnc_user }}"
    group: "{{ vnc_user }}"

- name: Ensure VNC passwd file exists
  ansible.builtin.file:
    path: "/home/{{ vnc_user }}/.vnc/passwd"
    state: touch
    mode: '0600'
    owner: "{{ vnc_user }}"
    group: "{{ vnc_user }}"
  become: yes

- name: Set VNC password
  ansible.builtin.command:
    cmd: echo "{{ vnc_password }}" | /usr/bin/vncpasswd -f
    chdir: "/home/{{ vnc_user }}/.vnc"
  become: yes


- name: Set xstartup file
  ansible.builtin.template:
    src: xstartup.j2
    dest: /home/{{ vnc_user }}/.vnc/xstartup
    mode: '0700'
    owner: "{{ vnc_user }}"
    group: "{{ vnc_user }}"
  become: yes


- name: Configure VNC server
  ansible.builtin.template:
    src: vncserver.j2
    dest: /etc/systemd/system/vncserver.service
  become: yes
  notify: reload systemd


- name: Start and enable VNC server service
  ansible.builtin.systemd:
    name: vncserver.service
    enabled: yes
    state: started
  become: yes
  notify: reload systemd



